# -*- coding: utf-8 -*-
"""Study Time Allocator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18EZ1X4BAuBqz-kAoxNnVChswmVTmUQ6a
"""

subjects = int(input("How many hours do you have?"))
study_hours = float(input("How many hours can you study per day?" ))
names = []
difficulties =[]

for i in range(subjects):
  name = input(f"Enter subhject {i+1} name: ")
  difficulty =int(input("Difficulty (1_5):"))
  names.append(name)
  difficulties.append(difficulty)

total_difficulty = sum(difficulties)

print("📚🕦 Your study plan:")

for i in range(subjects):
  hours = (difficulties[i] / total_difficulty) * study_hours

  h = int(hours)
  m = int((hours - h)*60)
  print(f"{names[i]}  \u200e -> {h} hours and {m} minutes per day ")